### ISSUE TITLE
사이드 메뉴 배경 투명화

### ISSUE THREAD

**Issue by mgdgc** [DeveloperAcademy-POSTECH/2023-A-MC3-WATERFUL#42]

**Comment by mgdgc** [comment]
@songmoro 현재 실행하면 SideBar가 HIG에 맞게 Glassmorphism으로 표시되는데, StageManager를 끄고 테스트 한번 부탁드립니다.

**Comment by songmoro** [comment]
@mgdgc 사이드바 불투명도 때문에 투명하지 않게 느껴졌었네요
확인했습니다.

**Comment by songmoro** [comment]
@mgdgc  사이드바 불투명도 때문에 투명하지 않게 느껴졌었네요
확인했습니다.
